//Generated by ChatGPT and edited
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

public class MouseDownButton : MonoBehaviour, IPointerDownHandler, IPointerUpHandler
{
    //private bool isPressed = false;
    private Button button;

    private void Awake()
    {
        button = GetComponent<Button>();
    }
    /*
    private void Update()
    {
        if (isPressed)
        {
            button.onClick.Invoke();
        }
    }
    */
    public void OnPointerDown(PointerEventData eventData)
    {
        //isPressed = true;
        GameObject.FindGameObjectWithTag("Player").GetComponent<Player>().buttonClick = true;
        button.onClick.Invoke();
    }

    public void OnPointerUp(PointerEventData eventData)
    {
        GameObject.FindGameObjectWithTag("Player").GetComponent<Player>().buttonClick = false;
        //isPressed = false;
        // Optionally, you can manually trigger the button click event on mouse up
        //button.onClick.Invoke();
    }
}
